// Types + display helpers for the /data-quality page. The page reads the
// committed verification report (src/data/verification-report.json), which is
// regenerated by `npm run verify:data -- --report` (and weekly in CI) against
// live Wikidata/Wikipedia/GBIF/iNaturalist.

export type VerificationStatus = 'verified' | 'drifted' | 'na' | 'error';

export type SourceKey = 'wikidata' | 'wikipedia' | 'gbif' | 'inaturalist';

export interface SourceResult {
  status: VerificationStatus;
  detail: string;
  /** ISO timestamp of the individual check. */
  checkedAt: string;
}

export interface ReportSpecies {
  animalId: string;
  commonName: string;
  scientificName: string;
  conservationStatus: string;
  sources: Record<SourceKey, SourceResult>;
}

export interface VerificationReport {
  schemaVersion: number;
  generatedAt: string;
  generator: string;
  sourceOrder: SourceKey[];
  sourceLabels: Record<SourceKey, string>;
  totals: {
    species: number;
    fullyVerified: number;
    drifted: number;
    checks: number;
    perStatus: Record<VerificationStatus, number>;
  };
  species: ReportSpecies[];
}

export const STATUS_META: Record<
  VerificationStatus,
  { label: string; dot: string; badge: string; description: string }
> = {
  verified: {
    label: 'Verified',
    dot: 'bg-success-500',
    badge: 'bg-success-100 dark:bg-success-900/40 text-success-700 dark:text-success-300',
    description: 'Live source matches the recorded data.',
  },
  drifted: {
    label: 'Drifted',
    dot: 'bg-warning-500',
    badge: 'bg-warning-100 dark:bg-warning-900/40 text-warning-700 dark:text-warning-300',
    description: 'Live source disagrees with the recorded data.',
  },
  na: {
    label: 'N/A',
    dot: 'bg-secondary-300 dark:bg-secondary-600',
    badge: 'bg-secondary-100 dark:bg-secondary-800 text-secondary-500 dark:text-secondary-400',
    description: 'Not applicable — no signal from this source.',
  },
  error: {
    label: 'Error',
    dot: 'bg-danger-500',
    badge: 'bg-danger-100 dark:bg-danger-900/40 text-danger-700 dark:text-danger-300',
    description: 'The check failed to run against the live source.',
  },
};

/** Overall species row status: clean only when no source drifted/errored. */
export function speciesRowStatus(species: ReportSpecies): 'clean' | 'drifted' {
  const bad = (['wikidata', 'wikipedia', 'gbif', 'inaturalist'] as SourceKey[]).some(
    (k) => species.sources[k]?.status === 'drifted' || species.sources[k]?.status === 'error',
  );
  return bad ? 'drifted' : 'clean';
}

export function reportAgeDays(generatedAt: string): number {
  return Math.max(0, Math.floor((Date.now() - new Date(generatedAt).getTime()) / 86_400_000));
}

/** The weekly CI check window: reports older than this are stale. */
export const REPORT_MAX_AGE_DAYS = 7;

export function formatCheckedAt(iso: string): string {
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return iso;
  return d.toISOString().replace('T', ' ').slice(0, 16) + ' UTC';
}
